# Generated by Django 4.2.3 on 2023-08-16 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edad',
            name='fechaNacimiento',
        ),
    ]
