# Generated by Django 4.2.3 on 2023-08-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_remove_edad_fechanacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='direccionDeResidencia',
        ),
        migrations.DeleteModel(
            name='edad',
        ),
        migrations.DeleteModel(
            name='identificacion',
        ),
        migrations.DeleteModel(
            name='nombre',
        ),
    ]
