# Generated by Django 4.2.3 on 2023-08-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_cliente_producto_delete_direccionderesidencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='articulo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
